name: et_module_only
description: 'Disaggregation of energy demand from transport sector to hourly'
scenario_sets: # Select 0 or more of the scenario sets
- transport_energy_demand
- population
- gva
sector_models: # Select 1 or more of the sector models
- et_module
- energy_demand
- energy_supply
scenario_dependencies:
- source_scenario: population
  scenario_parameter: population
  sink_model: energy_demand
  model_input: population
- source_scenario: gva
  scenario_parameter: gva
  sink_model: energy_demand
  model_input: gva
- source_scenario: transport_energy_demand
  scenario_parameter: electricity
  sink_model: et_module
  model_input: electricity
model_dependencies:
- source_model: et_module
  output: electricity
  sink_model: energy_supply
  input: electricity
- source_model: energy_demand
  output: electricity
  sink_model: energy_supply
  input: electricity
max_iterations: 100
convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
